/* JavaScripts/searchData.js */

const searchData = [
  {
    title: "Homepage & System Dashboard",
    url: "index.html",
    category: "Home",
    keywords: ["home", "start", "landing", "front end", "engineer", "winnipeg"],
  },
  {
    title: "Treaty 1 Education Platform Case Study",
    url: "index.html#featured-work",
    category: "Work",
    keywords: [
      "portfolio",
      "projects",
      "treaty",
      "history",
      "education",
      "design",
      "ux",
    ],
  },
  {
    title: "Capabilities Matrix & Real Value",
    url: "index.html#about",
    category: "Home",
    keywords: [
      "skills",
      "capabilities",
      "responsive",
      "seo",
      "scaling",
      "business",
      "value",
    ],
  },
  {
    title: "Academic Foundation: PTEC Web Program",
    url: "index.html#academic-foundation",
    category: "Home",
    keywords: ["school", "ptec", "education", "learning", "student", "grade 9"],
  },
  {
    title: "Interactive Playground Laboratory",
    url: "work.html",
    category: "Work",
    keywords: [
      "lab",
      "experiments",
      "code",
      "playground",
      "tests",
      "animations",
      "hover",
    ],
  },
  {
    title: "Print Stylesheets & Offline Testing",
    url: "work.html#lab-print",
    category: "work",
    keywords: ["print", "offline", "document", "monochrome", "paper"],
  },
  {
    title: "Fluid Typography Math (Clamp)",
    url: "work.html#lab-fluid",
    category: "work",
    keywords: ["math", "clamp", "font", "typography", "scaling", "responsive"],
  },
  {
    title: "Developer Philosophy & Architecture Laws",
    url: "philosophy.html",
    category: "Philosophy",
    keywords: [
      "rules",
      "laws",
      "mindset",
      "approach",
      "manifesto",
      "design",
      "brutalism",
    ],
  },
  {
    title: "Cognitive Load & The Halo Effect",
    url: "philosophy.html#tenets",
    category: "Philosophy",
    keywords: [
      "psychology",
      "brain",
      "skimmers",
      "reading",
      "attention",
      "speed",
    ],
  },
  {
    title: "Operator Profile & Core Rig Constraints",
    url: "contact.html#personal-specs",
    category: "Contact",
    keywords: [
      "about",
      "me",
      "profile",
      "hobbies",
      "setup",
      "computer",
      "music",
      "drake",
    ],
  },
  {
    title: "Contact & Strategic Partnership",
    url: "contact.html",
    category: "Contact",
    keywords: [
      "email",
      "message",
      "hire",
      "work",
      "partnership",
      "form",
      "inquiry",
    ],
  },
  {
    title: "Strict Web Accessibility (WCAG)",
    url: "index.html#featured-work",
    category: "System",
    keywords: [
      "a11y",
      "accessible",
      "blind",
      "screen reader",
      "tab",
      "keyboard",
      "reduced motion",
    ],
  },
  {
    title: "System Color Preferences (Dark Mode)",
    url: "#",
    category: "System",
    keywords: ["dark", "light", "theme", "colors", "fouc", "toggle", "switch"],
  },
];
